# Generated by Django 5.0.6 on 2024-10-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VanityUrl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vanity_url', models.CharField(default='', max_length=32, unique=True)),
                ('target', models.CharField(default='', max_length=512)),
            ],
        ),
    ]
