# Generated by Django 5.0.6 on 2025-06-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanityurls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vanityurl',
            options={'verbose_name': 'Vanity URL'},
        ),
        migrations.AlterField(
            model_name='vanityurl',
            name='vanity_url',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
