# Generated by Django 5.0.6 on 2025-06-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanityurls', '0002_alter_vanityurl_options_alter_vanityurl_vanity_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanityurl',
            name='code',
            field=models.CharField(choices=[('301', '301 Moved Permanently'), ('302', '302 Found'), ('307', '307 Temporary Redirect'), ('308', '308 Permanent Redirect')], default='301', max_length=8),
        ),
        migrations.AlterField(
            model_name='vanityurl',
            name='vanity_url',
            field=models.CharField(max_length=255, unique=True, verbose_name='Redirect from'),
        ),
    ]
